postgres-replica:
  image: "nebirhos/postgres-replication"
  ports:
    - 5433:5432
  links:
    - postgres-master
  environment:
    REPLICATION_ROLE: replica
    POSTGRES_MASTER_SERVICE_HOST: postgres-master

postgres-master:
  image: "nebirhos/postgres-replication"
  ports:
    - 5432:5432
