version: '2'

services:

  postgres-primary:
    build: 
      context: "./"
      dockerfile: "primary.dockerfile"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_ROLE=primary
      
    ports:
      - 5432:5432

  postgres-replica:
    #image: "nebirhos/postgres-replication"
    build: 
      context: "./"
      dockerfile: "primary.dockerfile"
    ports:
      - 5433:5432
    links:
      - postgres-primary
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_ROLE=replica
      - POSTGRES_MASTER_SERVICE_HOST=postgres-primary
