version: '2'

services:
  postgres-replica:
    build: ./Dockerfile
    #image: "nebirhos/postgres-replication"
    ports:
      - 5433:5432
    links:
      - postgres-primary
    environment:
      - REPLICATION_ROLE=replica
      - POSTGRES_PRIMARY_SERVICE_HOST=postgres-primary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  postgres-primary:
    build: ./Dockerfile
    #image: "nebirhos/postgres-replication"
    ports:
      - 5432:5432
    environment:
      - REPLICATION_ROLE=primary
      - POSTGRES_PRIMARY_SERVICE_HOST=postgres-primary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
